api:
  url: "https://labs-api.oanda.com/v1/financing-rates?divisionId=4&tradingGroupId=1"
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
    Accept: "application/json, text/plain, */*"
database:
  file: "oanda_rates.db"
